apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: failed-pod-controller
  name: failed-pod-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: failed-pod-controller
  name: failed-pod-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: failed-pod-controller
  name: failed-pod-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: failed-pod-controller
subjects:
  - kind: ServiceAccount
    name: failed-pod-controller
